name: Job Status Dependency
on:
  push:
    branches:
      - release-test

jobs:
  use-always:
    runs-on: ubuntu-latest
    steps:
      - name: success
        run: 'echo "success"'
      - name: fail
        run: exit 1
      - name: failure
        run: 'echo "failure"'
        if: ${{ failure() }}
      - name: always
        run: 'echo "always"'
        if: ${{ always() }}
