on:
  push:
    branches:
      - 'link-project'
  issues:
    types: [opened, edited, milestoned]

jobs:
  link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          version: 1.15.x
      - name: Install GitHub CLI
        run: go get github.com/cli/cli
      - name: Check GitHub CLI Installation
        run: gh --version
