on: [issue]

jobs:
  link:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          apt-add-repository https://cli.github.com/packages
          apt update
          apt install gh
      - name: Check GitHub CLI Installation
        run: gh --version
